# Generated by Django 5.0.6 on 2024-06-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Zweryfikowany'),
        ),
    ]
