# Generated by Django 5.0.6 on 2024-07-11 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='Phone Verified'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Phone Verification Code'),
        ),
    ]
