# Generated by Django 5.0.6 on 2024-07-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myuser_is_phone_verified_myuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['id'], 'verbose_name': 'Użytkownik', 'verbose_name_plural': 'Użytkownicy'},
        ),
    ]
