# Generated by Django 5.0.6 on 2024-08-06 18:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='password_reset_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email_verification_expiry',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email_verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Phone Verification Code'),
        ),
    ]
