# Generated by Django 5.0.6 on 2024-06-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("title2", models.CharField(default=None, max_length=50, null=True)),
                ("text", models.TextField(max_length=5000)),
                (
                    "element1",
                    models.TextField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
                (
                    "element2",
                    models.TextField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
                (
                    "element3",
                    models.TextField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
                (
                    "element4",
                    models.TextField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
            ],
        ),
    ]
