# Generated by Django 5.0.6 on 2024-06-22 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'verbose_name': 'Aukcja', 'verbose_name_plural': 'Aukcje'},
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Oferta', 'verbose_name_plural': 'Oferty'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Sekcja', 'verbose_name_plural': 'Sekcje'},
        ),
        migrations.AlterField(
            model_name='auction',
            name='artist',
            field=models.CharField(max_length=200, verbose_name='Artysta'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Aktualna oferta'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='dimensions',
            field=models.CharField(max_length=200, verbose_name='Wymiary'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='auction_images/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='medium',
            field=models.CharField(max_length=200, verbose_name='Technika'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='year',
            field=models.IntegerField(verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='app.auction', verbose_name='Aukcja'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='section',
            name='element1',
            field=models.TextField(blank=True, default=None, max_length=650, null=True, verbose_name='Element 1'),
        ),
        migrations.AlterField(
            model_name='section',
            name='element2',
            field=models.TextField(blank=True, default=None, max_length=650, null=True, verbose_name='Element 2'),
        ),
        migrations.AlterField(
            model_name='section',
            name='element3',
            field=models.TextField(blank=True, default=None, max_length=650, null=True, verbose_name='Element 3'),
        ),
        migrations.AlterField(
            model_name='section',
            name='element4',
            field=models.TextField(blank=True, default=None, max_length=650, null=True, verbose_name='Element 4'),
        ),
        migrations.AlterField(
            model_name='section',
            name='text',
            field=models.TextField(blank=True, default=None, max_length=5000, verbose_name='Tekst'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Tytuł 2'),
        ),
    ]
