# Generated by Django 5.0.6 on 2024-06-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_auction_options_alter_bid_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('artist', models.CharField(max_length=200, verbose_name='Artysta')),
                ('description', models.TextField(verbose_name='Opis')),
                ('image', models.ImageField(upload_to='gallery_images/', verbose_name='Zdjęcie')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerie',
            },
        ),
    ]
