# Generated by Django 5.0.6 on 2024-07-11 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_galleryitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('title2', models.CharField(blank=True, max_length=200, null=True)),
                ('title3', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exhibitions/')),
                ('element1', models.TextField(blank=True, max_length=20000, null=True)),
                ('element2', models.TextField(blank=True, max_length=20000, null=True)),
                ('element3', models.TextField(blank=True, max_length=20000, null=True)),
                ('element4', models.TextField(blank=True, max_length=20000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/', verbose_name='Zdjecie'),
        ),
        migrations.AddField(
            model_name='section',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/', verbose_name='Zdjecie'),
        ),
        migrations.AddField(
            model_name='section',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/', verbose_name='Zdjecie'),
        ),
        migrations.AddField(
            model_name='section',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/', verbose_name='Zdjecie'),
        ),
        migrations.AddField(
            model_name='section',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/', verbose_name='Zdjecie'),
        ),
        migrations.AddField(
            model_name='section',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/', verbose_name='Zdjecie'),
        ),
        migrations.AddField(
            model_name='section',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/', verbose_name='Zdjecie'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(verbose_name='Data zakoÅ„czenia'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='auction_images/', verbose_name='ZdjÄ™cie'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(max_length=200, verbose_name='TytuÅ‚'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UÅ¼ytkownik'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(upload_to='gallery_images/', verbose_name='ZdjÄ™cie'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='TytuÅ‚'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=75, verbose_name='TytuÅ‚'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title2',
            field=models.CharField(blank=True, default=None, max_length=75, null=True, verbose_name='TytuÅ‚ 2'),
        ),
    ]
