# Generated by Django 5.0.6 on 2024-07-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auctionwatcher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['id'], 'verbose_name': 'Aukcja', 'verbose_name_plural': 'Aukcje'},
        ),
        migrations.AlterModelOptions(
            name='auctionwatcher',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['id'], 'verbose_name': 'Oferta', 'verbose_name_plural': 'Oferty'},
        ),
        migrations.AlterModelOptions(
            name='exhibition',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['id'], 'verbose_name': 'Galeria', 'verbose_name_plural': 'Galerie'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['id'], 'verbose_name': 'Sekcja', 'verbose_name_plural': 'Sekcje'},
        ),
    ]
