# Generated by Django 5.0.6 on 2024-07-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_auction_options_alter_auctionwatcher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('auction_id', models.PositiveIntegerField(db_index=True)),
                ('last_notified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_email'], name='app_notific_user_em_c875ba_idx'), models.Index(fields=['auction_id'], name='app_notific_auction_b7e4a8_idx'), models.Index(fields=['last_notified_at'], name='app_notific_last_no_5bbf16_idx')],
                'unique_together': {('user_email', 'auction_id')},
            },
        ),
    ]
