# Generated by Django 5.0.6 on 2024-08-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='buy_now_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena kup teraz'),
        ),
    ]
