# Generated by Django 5.0.6 on 2024-10-28 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auction_buy_now_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(verbose_name='Data zakonczenia'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='auction_images/', verbose_name='Zdjecie'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytul'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytul')),
                ('artist', models.CharField(max_length=200, verbose_name='Artysta')),
                ('year', models.IntegerField(verbose_name='Rok')),
                ('medium', models.CharField(max_length=200, verbose_name='Technika')),
                ('dimensions', models.CharField(max_length=200, verbose_name='Wymiary')),
                ('description', models.TextField(verbose_name='Opis')),
                ('image', models.ImageField(default='default.jpg', upload_to='items_images/', verbose_name='Zdjecie')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena kup teraz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('buyer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Przedmiot',
                'verbose_name_plural': 'Przedmioty',
                'ordering': ['id'],
            },
        ),
    ]
