# Generated by Django 5.0.6 on 2024-12-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_category_galleryitem_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
    ]
